Repository Noostak/noostak_server, pull requests merged in 2025-01, with the labels that each got.

#8 ✨ feat: 멤버 도메인 엔티티 및 VO 구현
  src/main/java/org/noostak/server/group/domain/Group.java
  src/main/java/org/noostak/server/like/domain/Like.java
  src/main/java/org/noostak/server/member/domain/Member.java
  src/main/java/org/noostak/server/member/domain/MemberGroup.java
  src/main/java/org/noostak/server/member/domain/MemberName.java
  src/main/java/org/noostak/server/member/domain/vo/AccountStatus.java
  src/main/java/org/noostak/server/member/domain/vo/MemberName.java
  src/main/java/org/noostak/server/member/domain/vo/ProfileImageUrl.java
  src/main/java/org/noostak/server/member/domain/vo/SocialId.java
  src/main/java/org/noostak/server/member/domain/vo/SocialType.java
  src/main/java/org/noostak/server/option/api/temp
  src/main/java/org/noostak/server/option/application/temp
  src/main/java/org/noostak/server/option/domain/Option.java
  src/main/java/org/noostak/server/option/dto/temp
  src/main/java/org/noostak/server/option/exception/temp
  src/test/java/org/noostak/server/member/domain/vo/MemberNameTest.java
  src/test/java/org/noostak/server/member/domain/vo/ProfileImageUrlTest.java
  src/test/java/org/noostak/server/member/domain/vo/SocialIdTest.java
Labels: ✨ feat, 🐋 장순 🐋

#11 🔀 Merge: develop -> main | 신규 기능 및 개선 사항 배포
  src/main/java/org/noostak/server/appointment/api/temp
  src/main/java/org/noostak/server/appointment/application/temp
  src/main/java/org/noostak/server/appointment/domain/Appointment.java
  src/main/java/org/noostak/server/appointment/domain/AppointmentAvailability.java
  src/main/java/org/noostak/server/appointment/domain/AppointmentMember.java
  src/main/java/org/noostak/server/appointment/domain/AppointmentName.java
  src/main/java/org/noostak/server/appointment/domain/AppointmentStatus.java
  src/main/java/org/noostak/server/appointment/dto/temp
  src/main/java/org/noostak/server/appointment/exception/temp
  src/main/java/org/noostak/server/auth/api/temp
  src/main/java/org/noostak/server/auth/application/temp
  src/main/java/org/noostak/server/auth/domain/temp
  src/main/java/org/noostak/server/auth/dto/temp
  src/main/java/org/noostak/server/auth/exception/temp
  src/main/java/org/noostak/server/global/config/temp
  src/main/java/org/noostak/server/global/entity/BaseTimeEntity.java
  src/main/java/org/noostak/server/global/error/temp
  src/main/java/org/noostak/server/global/request/temp
  src/main/java/org/noostak/server/global/response/temp
  src/main/java/org/noostak/server/group/api/temp
  src/main/java/org/noostak/server/group/application/temp
  src/main/java/org/noostak/server/group/domain/Group.java
  src/main/java/org/noostak/server/group/domain/GroupName.java
  src/main/java/org/noostak/server/group/domain/InviteCode.java
  src/main/java/org/noostak/server/group/domain/InviteCodes.java
  src/main/java/org/noostak/server/group/dto/temp
  src/main/java/org/noostak/server/group/exception/temp
  src/main/java/org/noostak/server/infra/HomeController.java
  src/main/java/org/noostak/server/like/api/temp
  src/main/java/org/noostak/server/like/application/temp
  src/main/java/org/noostak/server/like/domain/Like.java
  src/main/java/org/noostak/server/like/dto/temp
  src/main/java/org/noostak/server/like/exception/temp
  src/main/java/org/noostak/server/member/api/temp
  src/main/java/org/noostak/server/member/application/temp
  src/main/java/org/noostak/server/member/domain/Member.java
  src/main/java/org/noostak/server/member/domain/MemberGroup.java
  src/main/java/org/noostak/server/member/domain/vo/AccountStatus.java
  src/main/java/org/noostak/server/member/domain/vo/MemberName.java
  src/main/java/org/noostak/server/member/domain/vo/ProfileImageUrl.java
  src/main/java/org/noostak/server/member/domain/vo/SocialId.java
  src/main/java/org/noostak/server/member/domain/vo/SocialType.java
  src/main/java/org/noostak/server/member/dto/temp
  src/main/java/org/noostak/server/member/exception/temp
  src/test/java/org/noostak/server/member/domain/vo/MemberNameTest.java
  src/test/java/org/noostak/server/member/domain/vo/ProfileImageUrlTest.java
  src/test/java/org/noostak/server/member/domain/vo/SocialIdTest.java
Labels: 🧬 merge, 🐋 장순 🐋

#13 🔀 Merge: develop -> main | 그룹 도메인 엔티티 및 VO 구현 사항 배포
  src/main/java/org/noostak/server/group/domain/Group.java
  src/main/java/org/noostak/server/group/domain/GroupInviteCode.java
  src/main/java/org/noostak/server/group/domain/InviteCodes.java
  src/main/java/org/noostak/server/group/domain/vo/Code.java
  src/main/java/org/noostak/server/group/domain/vo/GroupImageUrl.java
  src/main/java/org/noostak/server/group/domain/vo/GroupMemberCount.java
  src/main/java/org/noostak/server/group/domain/vo/GroupName.java
  src/test/java/org/noostak/server/group/domain/vo/CodeTest.java
  src/test/java/org/noostak/server/group/domain/vo/GroupImageUrlTest.java
  src/test/java/org/noostak/server/group/domain/vo/GroupMemberCountTest.java
  src/test/java/org/noostak/server/group/domain/vo/GroupNameTest.java
Labels: 🧬 merge, 🐋 장순 🐋

#17 🔀 Merge: develop -> main | 그룹 도메인 엔티티 및 VO 구현 반영
  src/main/java/org/noostak/server/appointment/domain/Appointment.java
  src/main/java/org/noostak/server/appointment/domain/AppointmentMember.java
  src/main/java/org/noostak/server/appointment/domain/Option.java
  src/main/java/org/noostak/server/appointment/domain/vo/AppointMemberCount.java
  src/main/java/org/noostak/server/appointment/domain/vo/AppointmentAvailability.java
  src/main/java/org/noostak/server/appointment/domain/vo/AppointmentCategory.java
  src/main/java/org/noostak/server/appointment/domain/vo/AppointmentName.java
  src/main/java/org/noostak/server/appointment/domain/vo/AppointmentStatus.java
  src/main/java/org/noostak/server/group/domain/Group.java
  src/test/java/org/noostak/server/appointment/domain/OptionTest.java
  src/test/java/org/noostak/server/appointment/domain/vo/AppointMemberCountTest.java
  src/test/java/org/noostak/server/appointment/domain/vo/AppointmentNameTest.java
Labels: 🧬 merge, 🐋 장순 🐋

#19 ✨ feat: 좋아요 도메인 엔티티 및 VO 구현
  src/main/java/org/noostak/server/like/domain/Like.java
  src/main/java/org/noostak/server/like/domain/vo/LikesCount.java
  src/test/java/org/noostak/server/like/domain/vo/LikesCountTest.java
Labels: ✨ feat, 🐋 장순 🐋

#20 🔀 Merge: develop -> main | 좋아요 도메인 엔티티 및 VO 구현 반영
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/DOCKER-CD-PROD.yml
  src/main/java/org/noostak/server/like/domain/Like.java
  src/main/java/org/noostak/server/like/domain/vo/LikesCount.java
  src/test/java/org/noostak/server/like/domain/vo/LikesCountTest.java
Labels: 🧬 merge, 🐋 장순 🐋

#24 [feat] 공통 예외 및 성공 응답 처리 구조 설계 및 구현
  src/main/java/org/noostak/server/global/error/core/BaseException.java
  src/main/java/org/noostak/server/global/error/core/ErrorCode.java
  src/main/java/org/noostak/server/global/error/core/ErrorResponse.java
  src/main/java/org/noostak/server/global/error/handler/GlobalErrorCode.java
  src/main/java/org/noostak/server/global/error/handler/GlobalExceptionHandler.java
  src/main/java/org/noostak/server/global/error/temp
  src/main/java/org/noostak/server/global/success/core/SuccessResponse.java
  src/main/java/org/noostak/server/global/success/handler/SuccessCode.java
  src/main/java/org/noostak/server/group/common/GroupErrorCode.java
  src/main/java/org/noostak/server/group/common/GroupException.java
  src/main/java/org/noostak/server/group/common/GroupSuccessCode.java
  src/main/java/org/noostak/server/group/exception/temp
Labels: ✨ feat, 🐋 장순 🐋

#25 🔀 Merge: develop -> main | 공통 예외 및 성공 응답 처리 구조 설계 및 구현
  src/main/java/org/noostak/server/global/error/core/BaseException.java
  src/main/java/org/noostak/server/global/error/core/ErrorCode.java
  src/main/java/org/noostak/server/global/error/core/ErrorResponse.java
  src/main/java/org/noostak/server/global/error/handler/GlobalErrorCode.java
  src/main/java/org/noostak/server/global/error/handler/GlobalExceptionHandler.java
  src/main/java/org/noostak/server/global/error/temp
  src/main/java/org/noostak/server/global/success/core/SuccessResponse.java
  src/main/java/org/noostak/server/global/success/handler/SuccessCode.java
  src/main/java/org/noostak/server/group/common/GroupErrorCode.java
  src/main/java/org/noostak/server/group/common/GroupException.java
  src/main/java/org/noostak/server/group/common/GroupSuccessCode.java
  src/main/java/org/noostak/server/group/exception/temp
Labels: 🧬 merge, 🐋 장순 🐋

#27 [refactor] group 및 like 테이블 이름 예약어 충돌 해결
  src/main/java/org/noostak/server/group/domain/Group.java
  src/main/java/org/noostak/server/like/domain/Like.java
Labels: ✨ feat, 🐋 장순 🐋

#28 [refactor] group 및 like 테이블 이름 예약어 충돌 해결
  src/main/java/org/noostak/server/group/domain/Group.java
  src/main/java/org/noostak/server/like/domain/Like.java
Labels: ♻️ refactor, 🐋 장순 🐋

#30 🔀 Merge: develop -> main | 그룹 조회 API 구현
  src/main/java/org/noostak/server/ServerApplication.java
  src/main/java/org/noostak/server/group/api/GroupController.java
  src/main/java/org/noostak/server/group/api/temp
  src/main/java/org/noostak/server/group/application/GroupService.java
  src/main/java/org/noostak/server/group/application/temp
  src/main/java/org/noostak/server/group/common/GroupSuccessCode.java
  src/main/java/org/noostak/server/group/domain/Group.java
  src/main/java/org/noostak/server/group/domain/GroupRepository.java
  src/main/java/org/noostak/server/group/dto/response/GroupResponse.java
  src/main/java/org/noostak/server/group/dto/response/GroupsResponse.java
  src/main/java/org/noostak/server/group/dto/temp
  src/test/java/org/noostak/server/group/api/GroupControllerTest.java
  src/test/java/org/noostak/server/group/application/GroupServiceTest.java
  src/test/java/org/noostak/server/group/domain/GroupRepositoryTest.java
Labels: 🧬 merge, 🐋 장순 🐋

#34 [refactor] SuccessCode 및 SuccessResponse 코드 구조 개선
  src/main/java/org/noostak/server/global/success/core/SuccessResponse.java
  src/main/java/org/noostak/server/global/success/handler/SuccessCode.java
  src/main/java/org/noostak/server/group/common/GroupSuccessCode.java
Labels: ♻️ refactor, 🐋 장순 🐋

#37 🔀 Merge: develop -> main | SuccessCode 및 SuccessResponse 코드 구조 개선
  src/main/java/org/noostak/server/global/success/core/SuccessResponse.java
  src/main/java/org/noostak/server/global/success/handler/SuccessCode.java
  src/main/java/org/noostak/server/group/common/GroupSuccessCode.java
Labels: 🧬 merge, 🐋 장순 🐋

#35 [✨ feat] 그룹 생성 API 구현
  src/main/java/org/noostak/server/group/api/GroupController.java
  src/main/java/org/noostak/server/group/application/GroupService.java
  src/main/java/org/noostak/server/group/application/InviteCodeGenerator.java
  src/main/java/org/noostak/server/group/common/GroupErrorCode.java
  src/main/java/org/noostak/server/group/common/GroupSuccessCode.java
  src/main/java/org/noostak/server/group/config/InviteCodeGeneratorConfig.java
  src/main/java/org/noostak/server/group/domain/DefaultInviteCodePolicy.java
  src/main/java/org/noostak/server/group/domain/Group.java
  src/main/java/org/noostak/server/group/domain/InviteCodePolicy.java
  src/main/java/org/noostak/server/group/domain/vo/Code.java
  src/main/java/org/noostak/server/group/domain/vo/GroupImageUrl.java
  src/main/java/org/noostak/server/group/domain/vo/GroupMemberCount.java
  src/main/java/org/noostak/server/group/domain/vo/GroupName.java
  src/main/java/org/noostak/server/group/dto/request/GroupCreateRequest.java
  src/main/java/org/noostak/server/group/dto/response/GroupCreateResponse.java
  src/main/java/org/noostak/server/member/domain/Member.java
  src/main/java/org/noostak/server/member/domain/MemberRepository.java
  src/test/java/org/noostak/server/group/api/GetAllGroupsControllerTest.java
  src/test/java/org/noostak/server/group/application/GroupServiceTest.java
  src/test/java/org/noostak/server/group/application/groupService/CreateGroupServiceTest.java
  src/test/java/org/noostak/server/group/application/groupService/GetAllGroupsServiceTest.java
  src/test/java/org/noostak/server/group/domain/vo/CodeTest.java
  src/test/java/org/noostak/server/group/domain/vo/GroupImageUrlTest.java
  src/test/java/org/noostak/server/group/domain/vo/GroupMemberCountTest.java
  src/test/java/org/noostak/server/group/domain/vo/GroupNameTest.java
  src/test/java/org/noostak/server/member/domain/MemberRepositoryTest.java
Labels: ✨ feat, 🐋 장순 🐋

#39 🔀Merge: develop -> main | 그룹 생성 API 구현
  src/main/java/org/noostak/server/group/api/GroupController.java
  src/main/java/org/noostak/server/group/application/GroupService.java
  src/main/java/org/noostak/server/group/application/InviteCodeGenerator.java
  src/main/java/org/noostak/server/group/common/GroupErrorCode.java
  src/main/java/org/noostak/server/group/common/GroupSuccessCode.java
  src/main/java/org/noostak/server/group/config/InviteCodeGeneratorConfig.java
  src/main/java/org/noostak/server/group/domain/DefaultInviteCodePolicy.java
  src/main/java/org/noostak/server/group/domain/Group.java
  src/main/java/org/noostak/server/group/domain/InviteCodePolicy.java
  src/main/java/org/noostak/server/group/domain/vo/Code.java
  src/main/java/org/noostak/server/group/domain/vo/GroupImageUrl.java
  src/main/java/org/noostak/server/group/domain/vo/GroupMemberCount.java
  src/main/java/org/noostak/server/group/domain/vo/GroupName.java
  src/main/java/org/noostak/server/group/dto/request/GroupCreateRequest.java
  src/main/java/org/noostak/server/group/dto/response/GroupCreateResponse.java
  src/main/java/org/noostak/server/member/domain/Member.java
  src/main/java/org/noostak/server/member/domain/MemberRepository.java
  src/test/java/org/noostak/server/group/api/GetAllGroupsControllerTest.java
  src/test/java/org/noostak/server/group/application/GroupServiceTest.java
  src/test/java/org/noostak/server/group/application/groupService/CreateGroupServiceTest.java
  src/test/java/org/noostak/server/group/application/groupService/GetAllGroupsServiceTest.java
  src/test/java/org/noostak/server/group/domain/vo/CodeTest.java
  src/test/java/org/noostak/server/group/domain/vo/GroupImageUrlTest.java
  src/test/java/org/noostak/server/group/domain/vo/GroupMemberCountTest.java
  src/test/java/org/noostak/server/group/domain/vo/GroupNameTest.java
  src/test/java/org/noostak/server/member/domain/MemberRepositoryTest.java
Labels: 🧬 merge, 🐋 장순 🐋

#32 ✨[feat] JWT를 활용한 토큰 발급
  build.gradle
  src/main/java/org/noostak/server/auth/application/DefaultJwtClaimsBuilder.java
  src/main/java/org/noostak/server/auth/application/JwtAccessTokenProvider.java
  src/main/java/org/noostak/server/auth/application/JwtClaimsBuilder.java
  src/main/java/org/noostak/server/auth/application/JwtRefreshTokenProvider.java
  src/main/java/org/noostak/server/auth/application/JwtTokenProvider.java
  src/main/java/org/noostak/server/auth/application/temp
  src/main/java/org/noostak/server/auth/common/AuthErrorCode.java
  src/main/java/org/noostak/server/auth/common/AuthException.java
  src/main/java/org/noostak/server/auth/common/AuthSuccessCode.java
  src/main/java/org/noostak/server/auth/exception/temp
  src/main/java/org/noostak/server/global/config/ClockConfig.java
  src/main/java/org/noostak/server/global/config/temp
  src/main/java/org/noostak/server/group/common/GroupSuccessCode.java
  src/main/java/org/noostak/server/member/domain/repository/MemberRepository.java
  src/test/java/org/noostak/server/auth/application/JwtAccessTokenProviderTest.java
  src/test/java/org/noostak/server/auth/application/JwtRefreshTokenProviderTest.java
Labels: ✨ feat, 🌼 채영 🌼

#43 🔀Merge: develop -> main | JWT를 이용한 토큰 발급
  build.gradle
  src/main/java/org/noostak/server/auth/application/DefaultJwtClaimsBuilder.java
  src/main/java/org/noostak/server/auth/application/JwtAccessTokenProvider.java
  src/main/java/org/noostak/server/auth/application/JwtClaimsBuilder.java
  src/main/java/org/noostak/server/auth/application/JwtRefreshTokenProvider.java
  src/main/java/org/noostak/server/auth/application/JwtTokenProvider.java
  src/main/java/org/noostak/server/auth/application/temp
  src/main/java/org/noostak/server/auth/common/AuthErrorCode.java
  src/main/java/org/noostak/server/auth/common/AuthException.java
  src/main/java/org/noostak/server/auth/common/AuthSuccessCode.java
  src/main/java/org/noostak/server/auth/exception/temp
  src/main/java/org/noostak/server/global/config/ClockConfig.java
  src/main/java/org/noostak/server/global/config/temp
  src/main/java/org/noostak/server/group/common/GroupSuccessCode.java
  src/main/java/org/noostak/server/member/domain/repository/MemberRepository.java
  src/test/java/org/noostak/server/auth/application/JwtAccessTokenProviderTest.java
  src/test/java/org/noostak/server/auth/application/JwtRefreshTokenProviderTest.java
Labels: 🧬 merge

#45 ✨[feat] Staging 서버 구축
  .github/workflows/DOCKER-CD-STAGING.yml
  Dockerfile-staging
  src/main/java/org/noostak/server/member/domain/repository/MemberRepository.java
Labels: ✨ feat, 🌼 채영 🌼

#46 🔀Merge: develop -> main | Staging 서버 구축
  .github/workflows/DOCKER-CD-STAGING.yml
  Dockerfile-staging
  src/main/java/org/noostak/server/member/domain/repository/MemberRepository.java
Labels: ✨ feat, 🌼 채영 🌼

#42 [✨feat] 약속 등록 API 구현
  src/main/java/org/noostak/server/appointment/api/AppointmentController.java
  src/main/java/org/noostak/server/appointment/api/temp
  src/main/java/org/noostak/server/appointment/application/AppointmentCreateService.java
  src/main/java/org/noostak/server/appointment/application/AppointmentService.java
  src/main/java/org/noostak/server/appointment/application/temp
  src/main/java/org/noostak/server/appointment/common/AppointmentErrorCode.java
  src/main/java/org/noostak/server/appointment/common/AppointmentException.java
  src/main/java/org/noostak/server/appointment/common/AppointmentSuccessCode.java
  src/main/java/org/noostak/server/appointment/domain/Appointment.java
  src/main/java/org/noostak/server/appointment/domain/AppointmentDateTime.java
  src/main/java/org/noostak/server/appointment/domain/AppointmentMember.java
  src/main/java/org/noostak/server/appointment/domain/AppointmentRepository.java
  src/main/java/org/noostak/server/appointment/domain/vo/AppointmentCategory.java
  src/main/java/org/noostak/server/appointment/domain/vo/AppointmentDuration.java
  src/main/java/org/noostak/server/appointment/dto/request/AppointmentCreateRequest.java
  src/main/java/org/noostak/server/appointment/dto/response/AppointmentCreateResponse.java
  src/main/java/org/noostak/server/appointment/dto/response/AppointmentDateTimeResponse.java
  src/main/java/org/noostak/server/appointment/dto/temp
  src/main/java/org/noostak/server/appointment/exception/temp
  src/test/java/org/noostak/server/appointment/api/AppointmentControllerTest.java
  src/test/java/org/noostak/server/appointment/application/AppointmentCreateServiceTest.java
  src/test/java/org/noostak/server/appointment/domain/AppointmentRepositoryTest.java
  src/test/java/org/noostak/server/appointment/domain/vo/AppointmentDurationTest.java
Labels: ✨ feat, 🐋 장순 🐋

#58 [refactor] AWS 설정값 적용방식 변경 및 JWT 토큰 발급 통합테스트
  src/main/java/org/noostak/server/auth/application/jwt/DefaultJwtClaimsBuilder.java
  src/main/java/org/noostak/server/auth/application/jwt/JwtAccessTokenProvider.java
  src/main/java/org/noostak/server/auth/application/jwt/JwtClaimsBuilder.java
  src/main/java/org/noostak/server/auth/application/jwt/JwtRefreshTokenProvider.java
  src/main/java/org/noostak/server/auth/application/jwt/JwtTokenProvider.java
  src/main/java/org/noostak/server/global/config/AwsConfig.java
  src/main/java/org/noostak/server/global/config/AwsProperties.java
  src/main/java/org/noostak/server/infra/S3Service.java
  src/test/java/org/noostak/server/auth/application/JwtAccessTokenProviderTest.java
  src/test/java/org/noostak/server/auth/application/JwtRefreshTokenProviderTest.java
  src/test/java/org/noostak/server/infra/S3ServiceTest.java
Labels: ♻️ refactor, 🌼 채영 🌼

#59 🔀 Merge: develop -> staging | AWS 설정값 적용방식 변경 및 JWT 토큰 발급 통합테스트
  src/main/java/org/noostak/server/auth/application/jwt/DefaultJwtClaimsBuilder.java
  src/main/java/org/noostak/server/auth/application/jwt/JwtAccessTokenProvider.java
  src/main/java/org/noostak/server/auth/application/jwt/JwtClaimsBuilder.java
  src/main/java/org/noostak/server/auth/application/jwt/JwtRefreshTokenProvider.java
  src/main/java/org/noostak/server/auth/application/jwt/JwtTokenProvider.java
  src/main/java/org/noostak/server/global/config/AwsConfig.java
  src/main/java/org/noostak/server/global/config/AwsProperties.java
  src/main/java/org/noostak/server/infra/S3Service.java
  src/test/java/org/noostak/server/auth/application/JwtAccessTokenProviderTest.java
  src/test/java/org/noostak/server/auth/application/JwtRefreshTokenProviderTest.java
  src/test/java/org/noostak/server/infra/S3ServiceTest.java
Labels: 🧬 merge, 🌼 채영 🌼

#60 🔀 Merge: staging -> main | AWS 설정값 적용방식 변경 및 JWT 토큰 발급 통합테스트
  src/main/java/org/noostak/server/auth/application/jwt/DefaultJwtClaimsBuilder.java
  src/main/java/org/noostak/server/auth/application/jwt/JwtAccessTokenProvider.java
  src/main/java/org/noostak/server/auth/application/jwt/JwtClaimsBuilder.java
  src/main/java/org/noostak/server/auth/application/jwt/JwtRefreshTokenProvider.java
  src/main/java/org/noostak/server/auth/application/jwt/JwtTokenProvider.java
  src/main/java/org/noostak/server/global/config/AwsConfig.java
  src/main/java/org/noostak/server/global/config/AwsProperties.java
  src/main/java/org/noostak/server/infra/S3Service.java
  src/test/java/org/noostak/server/auth/application/JwtAccessTokenProviderTest.java
  src/test/java/org/noostak/server/auth/application/JwtRefreshTokenProviderTest.java
  src/test/java/org/noostak/server/infra/S3ServiceTest.java
Labels: 🧬 merge, 🌼 채영 🌼

#62 [♻️refactor] 테스트 코드 의존성 분리 및 S3 적용
  src/main/java/org/noostak/server/appointment/api/AppointmentController.java
  src/main/java/org/noostak/server/appointment/application/AppointmentCreateService.java
  src/main/java/org/noostak/server/appointment/application/AppointmentService.java
  src/main/java/org/noostak/server/group/api/GroupController.java
  src/main/java/org/noostak/server/group/api/temp
  src/main/java/org/noostak/server/group/application/GroupService.java
  src/main/java/org/noostak/server/group/application/temp
  src/main/java/org/noostak/server/group/domain/Group.java
  src/main/java/org/noostak/server/group/dto/request/GroupCreateRequest.java
  src/main/java/org/noostak/server/group/dto/response/GroupCreateResponse.java
  src/main/java/org/noostak/server/group/dto/temp
  src/main/java/org/noostak/server/infra/FileStorageService.java
  src/main/java/org/noostak/server/infra/S3Service.java
  src/test/java/org/noostak/server/appointment/api/AppointmentControllerTest.java
  src/test/java/org/noostak/server/appointment/application/AppointmentCreateServiceTest.java
  src/test/java/org/noostak/server/appointment/domain/AppointmentRepositoryTest.java
  src/test/java/org/noostak/server/global/config/TestSecurityConfig.java
  src/test/java/org/noostak/server/group/api/GetAllGroupsControllerTest.java
  src/test/java/org/noostak/server/group/application/groupService/CreateGroupServiceTest.java
  src/test/java/org/noostak/server/group/application/groupService/GetAllGroupsServiceTest.java
  src/test/java/org/noostak/server/group/domain/GroupRepositoryTest.java
  src/test/java/org/noostak/server/infra/MockFileStorageService.java
  src/test/java/org/noostak/server/member/domain/MemberRepositoryTest.java
Labels: ♻️ refactor, 🐋 장순 🐋

#64 🔀Merge: develop -> staging | 테스트 코드 의존성 분리
  src/main/java/org/noostak/server/appointment/api/AppointmentController.java
  src/main/java/org/noostak/server/appointment/application/AppointmentCreateService.java
  src/main/java/org/noostak/server/appointment/application/AppointmentService.java
  src/main/java/org/noostak/server/group/api/GroupController.java
  src/main/java/org/noostak/server/group/api/temp
  src/main/java/org/noostak/server/group/application/GroupService.java
  src/main/java/org/noostak/server/group/application/temp
  src/main/java/org/noostak/server/group/domain/Group.java
  src/main/java/org/noostak/server/group/dto/request/GroupCreateRequest.java
  src/main/java/org/noostak/server/group/dto/response/GroupCreateResponse.java
  src/main/java/org/noostak/server/group/dto/temp
  src/main/java/org/noostak/server/infra/FileStorageService.java
  src/main/java/org/noostak/server/infra/S3Service.java
  src/test/java/org/noostak/server/appointment/api/AppointmentControllerTest.java
  src/test/java/org/noostak/server/appointment/application/AppointmentCreateServiceTest.java
  src/test/java/org/noostak/server/appointment/domain/AppointmentRepositoryTest.java
  src/test/java/org/noostak/server/global/config/TestSecurityConfig.java
  src/test/java/org/noostak/server/group/api/GetAllGroupsControllerTest.java
  src/test/java/org/noostak/server/group/application/groupService/CreateGroupServiceTest.java
  src/test/java/org/noostak/server/group/application/groupService/GetAllGroupsServiceTest.java
  src/test/java/org/noostak/server/group/domain/GroupRepositoryTest.java
  src/test/java/org/noostak/server/infra/MockFileStorageService.java
  src/test/java/org/noostak/server/member/domain/MemberRepositoryTest.java
Labels: 🧬 merge, 🐋 장순 🐋

#67 [✨ feat] 약속 가능 시간 선택 API 구현
  src/main/java/org/noostak/server/appointment/api/AppointmentController.java
  src/main/java/org/noostak/server/appointment/application/AppointmentService.java
  src/main/java/org/noostak/server/appointment/common/AppointmentErrorCode.java
  src/main/java/org/noostak/server/appointment/common/AppointmentSuccessCode.java
  src/main/java/org/noostak/server/appointment/domain/AppointmentMember.java
  src/main/java/org/noostak/server/appointment/domain/AppointmentMemberDateTime.java
  src/main/java/org/noostak/server/appointment/domain/repository/AppointmentMemberRepository.java
  src/main/java/org/noostak/server/appointment/domain/repository/AppointmentRepository.java
  src/main/java/org/noostak/server/appointment/dto/request/AvailableTimesRequest.java
  src/main/java/org/noostak/server/member/domain/MemberGroup.java
  src/main/java/org/noostak/server/member/domain/vo/MemberGroupRepository.java
  src/test/java/org/noostak/server/appointment/api/AppointmentControllerTest.java
  src/test/java/org/noostak/server/appointment/application/AppointmentCreateServiceTest.java
  src/test/java/org/noostak/server/appointment/application/AppointmentSaveAvailableTimesTest.java
  src/test/java/org/noostak/server/appointment/domain/AppointmentMemberRepositoryTest.java
  src/test/java/org/noostak/server/appointment/domain/AppointmentRepositoryTest.java
  src/test/java/org/noostak/server/member/domain/MemberGroupRepositoryTest.java
Labels: ✨ feat, 🐋 장순 🐋

#68 🔀Merge: develop -> staging | 약속 가능 시간 선택 API 구현
  src/main/java/org/noostak/server/appointment/api/AppointmentController.java
  src/main/java/org/noostak/server/appointment/application/AppointmentService.java
  src/main/java/org/noostak/server/appointment/common/AppointmentErrorCode.java
  src/main/java/org/noostak/server/appointment/common/AppointmentSuccessCode.java
  src/main/java/org/noostak/server/appointment/domain/AppointmentMember.java
  src/main/java/org/noostak/server/appointment/domain/AppointmentMemberDateTime.java
  src/main/java/org/noostak/server/appointment/domain/repository/AppointmentMemberRepository.java
  src/main/java/org/noostak/server/appointment/domain/repository/AppointmentRepository.java
  src/main/java/org/noostak/server/appointment/dto/request/AvailableTimesRequest.java
  src/main/java/org/noostak/server/member/domain/MemberGroup.java
  src/main/java/org/noostak/server/member/domain/vo/MemberGroupRepository.java
  src/test/java/org/noostak/server/appointment/api/AppointmentControllerTest.java
  src/test/java/org/noostak/server/appointment/application/AppointmentCreateServiceTest.java
  src/test/java/org/noostak/server/appointment/application/AppointmentSaveAvailableTimesTest.java
  src/test/java/org/noostak/server/appointment/domain/AppointmentMemberRepositoryTest.java
  src/test/java/org/noostak/server/appointment/domain/AppointmentRepositoryTest.java
  src/test/java/org/noostak/server/member/domain/MemberGroupRepositoryTest.java
Labels: 🧬 merge, 🐋 장순 🐋

#66 [✨feat] S3 이미지 URL 반환 기능
  src/main/java/org/noostak/server/infra/S3Service.java
  src/main/java/org/noostak/server/infra/error/S3ErrorCode.java
  src/main/java/org/noostak/server/infra/error/S3Exception.java
  src/test/java/org/noostak/server/infra/S3ServiceTest.java
Labels: ✨ feat, 🌼 채영 🌼

#69 🔀Merge: develop -> staging | S3 이미지 URL 반환 기능
  src/main/java/org/noostak/server/infra/S3Service.java
  src/main/java/org/noostak/server/infra/error/S3ErrorCode.java
  src/main/java/org/noostak/server/infra/error/S3Exception.java
  src/test/java/org/noostak/server/infra/S3ServiceTest.java
Labels: 🧬 merge, 🌼 채영 🌼

#71 [♻️refactor] S3 이미지 반환 메서드 기능 분리
  src/main/java/org/noostak/server/infra/FileStorageService.java
  src/main/java/org/noostak/server/infra/ImageHandlerService.java
  src/main/java/org/noostak/server/infra/S3Service.java
  src/main/java/org/noostak/server/infra/error/S3ErrorCode.java
  src/test/java/org/noostak/server/infra/ImageHandlerServiceTest.java
  src/test/java/org/noostak/server/infra/MockFileStorageService.java
  src/test/java/org/noostak/server/infra/S3ServiceTest.java
Labels: ♻️ refactor, 🌼 채영 🌼

#73 🔀Merge: develop -> staging | S3 이미지 반환 메서드 기능 분리
  src/main/java/org/noostak/server/infra/FileStorageService.java
  src/main/java/org/noostak/server/infra/ImageHandlerService.java
  src/main/java/org/noostak/server/infra/S3Service.java
  src/main/java/org/noostak/server/infra/error/S3ErrorCode.java
  src/test/java/org/noostak/server/infra/ImageHandlerServiceTest.java
  src/test/java/org/noostak/server/infra/MockFileStorageService.java
  src/test/java/org/noostak/server/infra/S3ServiceTest.java
Labels: 🧬 merge, 🌼 채영 🌼
